title: Pravanjan Patra # your name (or website title) here
logo: "/Prav Pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>    
      Senior Manager - Data Science at Ugam Solutions - A Merkle Company
  <br><br>
  <a href="mailto:pravanjanpatra@gmail.com">pravanjanpatra@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/pravanjan-patra-51101b14/">LinkedIn Profile</a>
  <br>
  
theme: jekyll-theme-minimal
